### ISSUE TITLE
Plugin compatibility with Elementor page builder

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#108]
We have a customer who's trying to implement Web Monetization on his site and is running in to a number of issues. I'm wondering whether our plugin is compatible with Elementor page builder. 

https://vibefar.com/

After some testing, we changed the CSS Selectors to .container article, which allowed the gray members-only box to appear on appropriate posts. However, there's still other issues. The Content Settings in the plugin are currently set to Monetized and Public for posts.

Here's a few examples of what we're seeing (or not seeing):
- https://vibefar.com/exclusive-tracks/ - Set to Coil Members Only. We both had to refresh the page before the gray members-only box appeared. Also, there's no padlock (Top nav: "Music > Exclusives")
- https://vibefar.com/videos-list/ - Set to Use Default. Extension shows the post is monetized, but the donation bar never appears for non-members. Verified the "Use Donation Bar" option was checked.
- https://vibefar.com/music-store/ - Shows a padlock in the top nav (Music Store), shows monetized when visiting, but non-members can see the content
- In the customizer, Show Padlock is not selected

Ping me for the email thread, if needed.

**Comment by iamthomasbarrett** [comment]
JIRA ticket created: COIL-158

**Comment by iamthomasbarrett** [comment]
Example pages appear to have been removed. 

To investigate, ideally we would have an exact setup - with plugin settings and markup generated by the page builder.

Are we able to get the pages re-instated (and a copy of their css selector setting)?
