### ISSUE TITLE
Voluntary donation message not appearing for GeneratePress theme

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#112]
Using the GeneratePress theme, I can only see the voluntary donation message on Monetized and Public posts when I am in the WordPress Customizer as an admin. The message never appears when I view a Monetized and Public post as a user who is not signed in to the Coil extension. I've tried a number of different selector combinations to no avail. 

(This issue was reported to us by a customer, but I've been able to replicate the issue using the same theme in our test site.)

**Comment by iamthomasbarrett** [comment]
COIL-160

**Comment by iamthomasbarrett** [comment]
The out-of-the-box gated content selector is `.content-area .entry-content`.
For GeneratePress, change it to `.site-content .entry-content`.

This setting can be found under Coil > Global Settings > Advanced Config > CSS Selectors

**Comment by melissahenderson** [comment]
I'm checking in Firefox, Chrome, and Safari and the message isn't appearing after setting my selectors to what you've suggested. I also purged the WP Engine cache.

**Comment by iamthomasbarrett** [comment]
Can we get a copy of the site health output. Please email to support@coil.com.

See this Yoast article for details: https://yoast.com/wordpress-site-health/

That will help us to try setting up a copy of the broken setup and replicate the issue.

**Comment by iamthomasbarrett** [comment]
For sake of notifications - re: previous message. Please email support@coil.com with health output, do not reply to this message/comment.

Apologies for any confusion.

Thank you.
