### ISSUE TITLE
Coil plugin incompatible with Co-Authors Plus plugin

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#114]
We received a report that the Author pages on A LIST APART stopped appearing after installing the Coil WP plugin. When they logged in to the WP Admin, they saw this on the Author page:

![noname.png](https://images.zenhubusercontent.com/5db7323a1484010001787d52/11c33fd7-d9e8-418e-8ab1-1e6babbbb3c3)

Their WP Concierge fixed the issue and reported:

The Coil plugin added recently doesn't seem to play nicely with the Co-Authors Plus plugin we use to manage author bios on the site. It expects to find author IDs as integers, as core WP does it, instead of strings as Co-Authors Plus does it. In order to restore the author pages, we had to merge some changes to the Coil plugin. 

I would highly recommend bringing this to the attention of the plugin developer; since the plugin deals with monetization of publications, and Co-Authors Plus is a pretty common plugin used by multi-author publications, it seems like this is a case they'd like to accommodate. We're happy to participate in that process... 

--------
I have the patch they pushed. I'm not sure if it's appropriate to attach to this issue.

**Comment by marcperel** [comment]
This issue is related to #61
