### ISSUE TITLE
'Message' popups do not show outside of 'customize theme', no matter what CSS selectors are used

### ISSUE THREAD

**Issue by jamminjames** [coilhq/coil-wordpress-plugin#116]
I have tried every CSS selector combo I can think of, drawing from the "inspector" in the browser, but the "message" to the viewer does not show, unless I'm in the WP "Customize theme" feature. 

I have the "GeneratePress" theme, and have tried the suggested CSS selectors. I've also tried the Twenty-Twenty theme, with all other plugins deactivated, and still the “message” only shows while in Appearance>Customize, but not on any page outside of that on the live site.

I adjusted the CSS selectors in the plugin settings for the Twenty-Twenty theme, to “.post-inner .entry-content”, and tried many others as well.

I do NOT have the Coil browser extension installed, on purpose, since we are trying to reach people who have not yet joined Coil, and that is who the “message” is designed to address. 

The js shown when doing a page source does not ever actually fire, apparently, which could be the cause of the problem (nothing shows in the console).

Can someone direct me to a website where the “message” shows to the public correctly (even if they do not have the browser extension)? I’d love to see a working example.

**Comment by marcperel** [comment]
@jamminjames thanks for bringing this up.

We are going to release an update for the issue, but in the mean time what you can do is this:

- Go to Appearance > Customize
- Click on Coil Web Monetization > Options
- Check OFF Show a donation bar on posts that are monetized and public.
- Click Publish
- Check ON Show a donation bar on posts that are monetized and public.
- Click Publish

That should solve the issue of the popup no displaying. It should default to ON but it seems that's broken.

Let me know if this works.

**Comment by jamminjames** [comment]
That worked, thanks!
