### ISSUE TITLE
Plugin breaks gutenberg for custom post type

### ISSUE THREAD

**Issue by mougias** [coilhq/coil-wordpress-plugin#41]
select( 'core/editor' ).getEditedPostAttribute( 'meta' ) will return undefined, for post types that register without support for custom-fields.

**Comment by pragmatic-web** [comment]
@mougias thanks for the feedback. We can replicate and confirm this is now a known issue. 

This issue also affects reusable Gutenberg blocks so it's now a high priority to find a resolution for this.

**Comment by leo40leo** [comment]
> @mougias thanks for the feedback. We can replicate and confirm this is now a known issue.
> 
> This issue also affects reusable Gutenberg blocks so it's now a high priority to find a resolution for this.

Any progress on this? Looking forward to taking this plugin for a "ride".

**Comment by pragmatic-web** [comment]
This issue was fixed by https://github.com/coilhq/coil-wordpress-plugin/pull/42
