### ISSUE TITLE
Categories not saving monetization setting

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#43]
To reproduce:

1. Create a new category.
2. Set it to Coil Members Only.
3. Click Add New Category.
4. Edit the category you just made. The setting shows as Use Default.
5. Change the setting and click Update. The setting reverts back to Use Default.

**Comment by pragmatic-web** [comment]
Currently investigating.

**Comment by praghavaji** [comment]
I've picked this up now.

I have a fully configured and working local copy of the plugin and demo site and am getting stuck in.

Just letting y'all know..
