### ISSUE TITLE
Ability to view hidden posts with rdf feeds

### ISSUE THREAD

**Issue by traviscrist** [coilhq/coil-wordpress-plugin#44]
The Wordpress plugin of Coil does not protect the endpoint a hidden content showing in a feed on endpoint feed/rdf

Steps to reproduce
Check the website for various feed format. feed/rdf is not protected
https://coil12345.000webhostapp.com/2020/05/hello-world/feed/rss <- not vulnerable
https://coil12345.000webhostapp.com/2020/05/hello-world/feed/rss2 <- not vulnerable
https://coil12345.000webhostapp.com/2020/05/hello-world/feed/atom <- not vulnerable
https://coil12345.000webhostapp.com/2020/05/hello-world/feed/rdf <- vulnerable
Hidden contents are leaked via feed RDF format

**Comment by praghavaji** [comment]
As far as I can tell none of the feeds are respecting content restrictions. Who can I discuss this one with?

**Comment by traviscrist** [comment]
@praghavaji Are you sure about that. On the RDF one it seems to have the hidden content in it when compared to the others
