### ISSUE TITLE
Archive/index pages not respecting monetization setting

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#46]
The Coil plugin's settings control individual post types, not archives (including a homepage archive known as an index page). This means that content on archive pages is visible to all, regardless of any monetization settings. 

1. Create a page and set it to Coil Members Only. 
2. Go to Settings > Reading, and notice the "Your homepage displays" option. The default is set to "Your latest posts". 
3. Now go view the new page as a non-monetized user. You should see the gray Members Only box. 
4. Go back into Settings > Reading and change the option to "A static page", then select your new page as the homepage. 
5. Save your changes and view/refresh your new page again. You can see the Members Only content.

**Comment by traviscrist** [comment]
This needs to be done as a feature, its too much work to be done as part of support work.

**Comment by iamthomasbarrett** [comment]
COIL-155
