### ISSUE TITLE
Change label and description for "Incorrect browser setup" message in Customizer

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#49]
Change label in Customizing > Coil Web Monetization > Messages:

- **From:** Incorrect browser setup message
- **To:** Fully gated content message

Change description for the same message:

- **From:** This message is shown when content is set to be Coil Members Only, and visitor either isn't using a supported browser, or doesn't have the browser extension installed correctly.
- **To:** This message is shown when content is set to be Coil Members Only, and the visitor is using an unsupported browser, has the extension installed incorrectly, is logged out of their Coil account, or doesn't have a Coil Membership.

Then, move the message so that it appears before the "Fully gated excerpt message".

**Comment by praghavaji** [comment]
This is in pull-request. Should have that approved shortly.

**Comment by paulgibbs** [comment]
That PR is https://github.com/coilhq/coil-wordpress-plugin/pull/87 but it needs more work

**Comment by paulgibbs** [comment]
Above merged in
