### ISSUE TITLE
"Members Only" box language customization

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#50]
Some of the text that appears in the gray "Members Only" box isn't customizable. The text that **can** be customized is part of the "Incorrect browser setup / Fully gated content" message (see GH issue #49). Let me know if you have suggestions for better messaging.

Add the following to Customizing > Coil Web Monetization > Messages:

- **Label:** Fully gated content heading
- **Description:** This message is shown as the heading for the "Fully gated content" message below.
- **Default lang string:** This content is for Coil Members only!
- **Location:** Directly above the "Fully gated content" message

- **Label:** Fully gated content footer
- **Description:** This message is shown as the footer for the "Fully gated content" message above.
- **Default lang string:** This content is for Coil Members only! Coil requires the use of an extension which your browser might not support. Visit coil.com for more information.
- **Location:** Directly beneath the "Fully gated content" message

**Comment by praghavaji** [comment]
I've successfully added the customizer elements here locally. Looking good.

I just noticed that the message used when rendering fully gated content within the cusomizer is the one from the fully gated excerpt message. That doesn't seem right.

Who can I discuss this with?

**Comment by melissahenderson** [comment]
So long as the messaging itself is customizable for this iteration, I think we're good. We can tackle rewording default messaging in a different GH issue. @traviscrist Does this approach sound OK with you?

**Comment by traviscrist** [comment]
@melissahenderson yep that sounds good, we can always just change the default ourselves. I think they key thing is that the default should be easily changed by us just changing a string in the codebase.

**Comment by pragmatic-web** [comment]
@traviscrist @melissahenderson propose pausing this one as it'll be overwritten by proposed UX updates anyway?

**Comment by iamthomasbarrett** [comment]
Following JIRA migration ticket now here: COIL-153

**Comment by melissahenderson** [comment]
@pragmatic-web @traviscrist  Makes sense. I agree.
