### ISSUE TITLE
Customizable lock icon for Members Only content

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#51]
Allow users to select from pre-existing lock icons or upload their own icon so that the icon is consistent with the look and feel of their site.

**Comment by pragmatic-web** [comment]
Assets provided by Fabian @melissahenderson for your triage in due course.

[lock-icon.zip](https://github.com/coilhq/coil-wordpress-plugin/files/4780316/lock-icon.zip)
