### ISSUE TITLE
Customizable "Members Only" box

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#52]
Give users more control over the appearance of the gray box that appears on Coil Members Only pages for non-monetized visitors. 

Ideas for customization include, but aren't limited to:
- Allowing users to add images to the box
- Changing the color of:
-- the box itself
-- the horizontal rule
-- the text
-- the button fill*
-- the text within the button*

*So long as it doesn't affect how the button appears in the voluntary donation bar or list of pages/posts. We'll need to rethink this if the button always pulls its styling from the same resource.

**Comment by marcperel** [comment]
We are going to close this as we have plans to update the plugin with new designs.
