### ISSUE TITLE
Block-level settings not showing - duplicate nonce warning

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#55]
Block-level Coil Monetization settings not showing. Using a default theme with correct CSS selectors. Disabled all other plugins. The only console message was a warning about a duplicate nonce. 

Email with additional details attached to Accelo ticket #1270.

**Comment by praghavaji** [comment]
This is expected behaviour i think.

The block level configuration setting show only when the document level settings are set to 'Split content'. Which makes sense no?

**Comment by melissahenderson** [comment]
@pragmatic-web David, thoughts on this?

**Comment by pragmatic-web** [comment]
Hi @melissahenderson @praghavaji sorry for the slow response. Confirmed - this behaviour is as expected.

@praghavaji might be worth adding this to the QA test plan to ensure it's captured?

**Comment by praghavaji** [comment]
Apologies again for the delay here. I've not been receiving notifications from Github nor Zenhub. Investigating that presently.

Ok, I'll get this added to the test plan and move this ticket to done.

Thanks!
