### ISSUE TITLE
Add warning when payment pointer field is empty

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#56]
If the Payment Pointer field is empty (Coil Settings > Global Settings) and you click Save Changes, the page displays the message "Settings saved". We should include a warning message stating there's no pointer, but still save the configuration.

Unless we can display the message in a different colored panel or include a warning icon, we should preface the message with "Warning".

"Warning: You've not entered a payment pointer. A payment pointer is required to receive payments and for content gating to be recognized."

**Comment by praghavaji** [comment]
Jira ticket: https://jira.pragmatic.agency/browse/COISUP-6

**Comment by iamthomasbarrett** [comment]
Following JIRA migration ticket is: COIL-154
