### ISSUE TITLE
Update Coil plugin's header

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#59]
Currently, the Coil logo appears centered and in a white panel at the top of the plugin settings screens.

We want to update the header to match this:
![updated plugin header](https://user-images.githubusercontent.com/57110301/84716378-c14f3380-af27-11ea-9006-17dc38c859b4.png)

- Left-align
- Remove white panel
- Add new logo (attached) and add "Coil Web Monetization" as text

[coil-icn-32.svg.zip](https://github.com/coilhq/coil-wordpress-plugin/files/4783531/coil-icn-32.svg.zip)

**Comment by marcperel** [comment]
Fixed in PR 126
