### ISSUE TITLE
Proposed update minimum PHP version support to 7.2

### ISSUE THREAD

**Issue by pragmatic-web** [coilhq/coil-wordpress-plugin#65]
Current plugin supports PHP 7.1 but this is now EOL: **https://www.php.net/supported-versions.php**

Current WP recommended minimum version is PHP 7.3 but https://wordpress.org/about/stats/ show ~50% sites are still on PHP 7.2/7.3. Bumping minimum version would potentially affect ~9% of Coil plugin users according to those stats.

7.2 feels like a sensible step.

**Comment by praghavaji** [comment]
No issue type label here. I guess this is an enhancement?

**Comment by traviscrist** [comment]
Ya I think it would be, added the label

**Comment by iamthomasbarrett** [comment]
COIL-152
