### ISSUE TITLE
Characters appearing with escape characters

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#78]
While using the WordPress customizer to change a user-facing gating message, I noticed that escape characters are appearing.

![Screen Shot 2020-08-07 at 10 36 38 AM](https://user-images.githubusercontent.com/57110301/89672735-05144880-d89a-11ea-99b7-7f99d11708cd.png)

**Comment by melissahenderson** [comment]
Hemingway theme is used in the example.

**Comment by praghavaji** [comment]
Jira ticket: https://jira.pragmatic.agency/browse/COISUP-5

**Comment by praghavaji** [comment]
The pull request for this has been approved.

Who authorises a merge and deployment?

**Comment by melissahenderson** [comment]
@traviscrist Can you answer the question above? Have we created a formal process for this yet?

**Comment by iamthomasbarrett** [comment]
Following JIRA migration now here: COIL-151
