### ISSUE TITLE
Override WP default of 55 words for teaser text

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#79]
Customer feedback:

"if one could define an offset, after how many characters or sentences the monetized wordpress page/article gets blurred/overlayed with the "readable only for  Coil members"-message.In most cases the current position of the message is too short to tease the viewer for the entire article. Could look like this: (faked coil-plugin-screenshot)"

<img width="748" alt="Screen Shot 2020-08-10 at 10 32 51 AM" src="https://user-images.githubusercontent.com/57110301/89812389-e6f65480-daf4-11ea-9f54-e8d654bea721.png">

I'm not sure if there's a way to override the WordPress default of 55 words, but it's worth investigating. This would prevent users from needing to manually set an excerpt for every single article as long as they are OK with the first X words of their article being the teaser. 

Conversation ID cnv_9rpa61b

**Comment by pragmatic-web** [comment]
We can definitely look into this.

**Comment by MWcompeff** [comment]
I was able to change the number of words in front of the overlay by adding this to the function.php (or alternativly by using the snippets-plugin to inject this code). It also worked for the "only for coil members" overlay,

add_filter( 'excerpt_length', 'firstwd_excerpt_length' );
function firstwd_excerpt_length() { return 80;}

**Comment by pragmatic-web** [comment]
Great stuff @MWcompeff - you're right, this can just be changed as a standard WordPress filter so it's probably not something the Coil plugin should look to control.

Documentation here: https://developer.wordpress.org/reference/hooks/excerpt_length/
