### ISSUE TITLE
Embedded videos in a show-for-monetized-users block won't auto-load in the Hemingway theme

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#81]
Videos embedded in a "Show for monetized users" block, within the Hemingway theme, need to be kicked before they appear.

1. Sign in to Coil.
2. Go to https://pghunfiltered.com/2020/07/27/maddy-judgeton-on-how-to-protest/
3. See the text, then extra white space at the bottom (shown in screenshot). That space should have the video.
4. Right-click on the page and select Inspect Element. Doing this will make the video appear on the page. I've also seen this happen if I load the page in a tab, then drag the tab out of the browser window to isolate it.

<img width="725" alt="Screen Shot 2020-08-13 at 3 56 36 PM" src="https://user-images.githubusercontent.com/57110301/90195150-99d8e380-dd7d-11ea-96d4-496774c811f1.png">

I duplicated the issue on http://coilplugin.wpengine.com/ using the Hemingway theme. When I switched to the 2019 theme, the issue didn't occur. The site is set back to Hemingway. Also, the text that I have in the "Show for monetized users"  block appears, just not the video: http://coilplugin.wpengine.com/2020/05/gutenberg-split-show-for-monetized-users/

**Comment by traviscrist** [comment]
Let's triage this and see if we can determine why this is happening and how much effort it will be to fix.
