### ISSUE TITLE
Ability to view hidden posts with the source of web page

### ISSUE THREAD

**Issue by Naategh** [coilhq/coil-wordpress-plugin#82]
The plugin show content of posts that should be hidden in the source of the web page:

I'm using @traviscrist website to show a live demo:
View `view-source:https://coil12345.000webhostapp.com/2020/05/hello-world` then search for the `first`, You'll see the content of the post

**Comment by pragmatic-web** [comment]
Thanks for the issue @Naategh. This is related to #60 - in due course we plan to add more thorough content obfuscation using JS rather than CSS and verifying receipt of funds rather than relying on the API status alone. Closing the ticket on that basis.
