### ISSUE TITLE
Hide padlock and messaging when split post only has "always show" blocks

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#83]
If a post is set to Split Content, but all the content is public (always show), the Latest Posts page shouldn't show a padlock or the Coil messaging.

![Screen Shot 2020-08-17 at 12 09 03 PM](https://user-images.githubusercontent.com/57110301/90446811-e468a180-e096-11ea-8a3e-6f1ef76aeb85.png)

It looks like the plugin is only checking the Document-level Web Monetization setting and applying the padlock and messaging for anything marked as "Split Content".

**Comment by traviscrist** [comment]
This seems like an edge case that should not be used. Closing this since it doesn't make sense to fix it.
