### ISSUE TITLE
Messaging for "Hide for Monetized Users" is inaccurate when user is monetized

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#84]
Assumption: A page/post is set to Split Content and has a Hide for Monetized Users block.

As a web monetized user viewing the Latest Posts page, I see a message that the post has content for Coil Members only, when really the content is hidden from me.

<img width="673" alt="Screen Shot 2020-08-17 at 2 43 20 PM" src="https://user-images.githubusercontent.com/57110301/90448017-71145f00-e099-11ea-97b1-43853585f585.png">

I also question why I'm seeing a padlock on this type of post. What's the use case for showing a page/post as locked when all I have to do is sign out of Coil to see the content?

**Comment by traviscrist** [comment]
@melissahenderson lets follow up with Fabian on this one, we may just need to update the ux a little.
